name: counter_bloc
description: A new Flutter project.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  remote_state:
    path: ../../packages/remote_state
  bloc: ^8.0.0
  flutter_bloc: ^8.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
